### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by De1ain**
Related issue #34

### CODE REVIEW

**Comment by guytepper** [comment]
Amazing, thank you! I'll make sure it looks good in the UI tomorrow :)

**Comment by guytepper** [comment]
Hey, the main title is long and can't fit one line, is there a synonym we can use for it to keep staying on one line? 
Also, can you please translate the term `זמני רכבת ישראל`? 😊 That'd go to the App Store page

<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/13344923/156915227-b80e9782-4190-4695-8725-ceae4dbd43b1.png">Simulator Screen Shot - iPhone 12 - 2022-03-06 at 10 25 10</a>

**Comment by De1ain** [comment]
I finally managed to setup the env properly and run the project.
Regarding the main title - I can replace it entirely with a single short word "Поездка" (trip).
I've also changed some other strings, and fixed spaces.
And fixed/updated some code to support the newly added language.

**Comment by De1ain** [comment]
זמני רכבת ישראל - 
Расписания Израильской Железной Дороги
Or a shorter version (Ж/Д is a common abbreviation for railways):
Расписания Израильской Ж/Д

**Comment by guytepper** [comment]
Thanks a lot, Tim! It looks great 👏

If you'd like, there is the iOS Widget & Apple Watch app that can also be translated to Russian. 
I'll soon add info to #88 on how to approach that. Btw, are you running the app on Android / iOS? Windows / macOS?

**Comment by De1ain** [comment]
I'm on Android / Windows.

**Pull request merged**
