### PR TITLE
Fix stations filtering while searching stations

### PR DESCRIPTION
**Pull request by BelferMan**
https://github.com/guytepper/better-rail/issues/35

Removing hyphens, spaces, dots, parenthesis and commas from the stations and from the user input as well.
So inputs like:

.תל       אביב, השלום
תל - אביב השלום
תל אביב: השלום

will find the right station.

### CODE REVIEW

**Comment by BelferMan** [comment]
@guytepper 

Look at the station- 
באר שבע- צפון/אוניברסיטה

If we will use .replace(" - ", " ") the search wont work - because there is no space before the hyphen.
Of course I can just use .replace(" - ", " ") and fix the specific station name but its just an example for why 
.replace(/[\. ,:-]+/g, "") can be a better choice for extreme cases like that.
Your call :)

**Comment by guytepper** [comment]
Nice catch! Is that the only case where we face that problem?
If it is, we can add the necessary space before/after the hyphen. You can find the station name right [here](https://github.com/guytepper/better-rail/blob/main/app/data/stations.ts#L152) (note that the Russian & English stations also in need of spaces)

**Comment by ITAYC0HEN** [comment]
You can use a simple regex to cover all these cases in a single go.
Regardless, going for a fuzzy match is always a nice way to handle these things, including other typos

**Comment by guytepper** [comment]
Hi Megabeets! 

If the only use case we try to cover is as described in #35, I think that using fuzzy match or regex here will be an overkill since It'll be extremely rare for a user to type special characters in their input. 
We just try to make stations with hyphens show up if the user types the full station name.

**Comment by guytepper** [comment]
Author withdrawn

**Pull request closed without merging**
